version: "3.7"

services:
  proxy-nginx:
    container_name: proxy-nginx
    build:
      context: ./proxy/nginx/
    ports:
      - ${PORT}:80
    volumes:
      - ./proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web-nginx
      - api-nginx

  web-nginx:
    container_name: web-nginx
    build:
      context: ./web/nginx
    volumes:
      - ./web/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${WEB_DIR}:/home/cafe
      
  api-nginx:
    container_name: api-nginx
    build:
      context: ./api/nginx/
    volumes:
      - ./api/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${API_DIR}:/home/cafe
    depends_on:
      - api-php
      - api-mysql
    links:
      - api-php

  api-php:
    container_name: api-php
    build:
      context: ./api/php/
    volumes:
      - ./api/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ${API_DIR}:/home/cafe
    depends_on:
      - api-mysql
    environment:
      PMA_HOST: api-mysql
      PMA_USERE: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    links:
      - api-mysql

  api-mysql:
    container_name: api-mysql
    image: mysql:8.0
    platform: linux/x86_64
    volumes:
      - ${MYSQL_DIR}:/var/lib/mysql
    environment:
      #MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci